name: CI Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [11, 17, 21]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and run tests with Gradle
        run: ./gradlew clean test --info

      - name: Upload test reports as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: |
            build/reports/tests/
            build/test-results/
          retention-days: 7

      - name: Archive JUnit XML results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: junit-results
          path: build/test-results/test/*.xml
          retention-days: 7
