name: CI Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [17, 21]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and run tests with Gradle
        run: ./gradlew clean test jacocoTestReport --info

      - name: Upload test reports as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-reports-${{ matrix.java }}-${{ github.run_id }}
          path: |
            build/reports/tests/
            build/test-results/
            build/reports/jacoco/
          retention-days: 7